[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 5173

# Redirects are handled via public/_redirects 

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# カスタムヘッダー設定 - 長いURLを許可
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # キャッシュ設定
    Cache-Control = "public, max-age=0, must-revalidate"
    # URLの長さ制限を緩和するヘッダー
    Large-Allocation = "off"

# 共有リンク用の特別なリダイレクト
[[redirects]]
  from = "/shared/*"
  to = "/index.html"
  status = 200
  force = true

# 参加リンク用の特別なリダイレクト
[[redirects]]
  from = "/join-trip/*"
  to = "/index.html"
  status = 200
  force = true 