[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 5173

# Redirects are handled via public/_redirects 

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 